import Link from 'next/link';
import {validityLabel} from '@/lib/validity';
import { SuburbioApiClient } from '@/lib/api/client';
import { pageAccess } from '@/lib/permissions/guards';
import { can } from '@/lib/permissions/policy';
import { AccessUnavailable, ErrorState } from '@/components/admin/states';
import { safeError } from '@/lib/api/errors';
import { CategoryEditor } from '@/components/admin/category-editor';
export default async function Page({searchParams}:{searchParams:Promise<{page?:string;q?:string}>}){
  const admin=await pageAccess('PRODUCTS_READ','/admin/products');if(!admin)return <AccessUnavailable/>;
  const query=await searchParams; const page=Number(query.page??1),q=query.q??'';let result,categories;
  try{const client=new SuburbioApiClient();[result,categories]=await Promise.all([client.products(admin.discordId,page,q),client.categories(admin.discordId)]);}catch(error){const safe=safeError(error);return <ErrorState message={safe.body.error.message} reference={safe.body.error.reference}/>;}
  return <><div className="admin-title"><span className="admin-kicker">GESTÃO / CATÁLOGO</span><h1>Produtos e benefícios</h1><p>Catálogo central da Área VIP e do Crypto no jogo.</p></div>{can(admin,'PRODUCTS_CREATE')&&!admin.readOnly&&categories.data.items.some(c=>c.status==='active')&&<Link className="button small" href="/admin/products/new">Novo produto</Link>}<form className="admin-filter"><label>Buscar por identificador<input name="q" maxLength={100} defaultValue={q} placeholder="vip-cria"/></label><button className="button small">Buscar</button></form><div className="admin-panel"><div className="admin-panel-title"><h2>Produtos</h2><span>{result.data.total} registros</span></div><div className="admin-table-wrap"><table><thead><tr><th>Nome</th><th>Tipo</th><th>Validade</th><th>Canais</th><th>Status</th><th>Preço</th><th>Crypto</th><th>Estoque</th></tr></thead><tbody>{result.data.items.map(p=><tr key={p.id}><td><Link href={`/admin/products/${p.id}`}>{p.name}</Link></td><td>{p.delivery.deliveryType}</td><td>{validityLabel(p)}{p.renewable?" · Renovável":""}</td><td>{p.salesChannels.map(c=>c==='SITE_VIP'?'Área VIP':'Crypto no jogo').join(' · ')}</td><td>{p.status==='active'?'Ativo':p.status==='inactive'?'Inativo':'Arquivado'}</td><td>{(p.priceMinor/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td>{p.priceCrypto}</td><td>{p.stockMode==='UNLIMITED'?'Ilimitado':p.stockQuantity}</td></tr>)}</tbody></table></div>{result.data.items.length===0&&<p className="admin-empty">Nenhum produto cadastrado.</p>}<div className="admin-pagination"><span>Página {page}</span>{page>1&&<Link href={`?${new URLSearchParams({page:String(page-1),q})}`}>Anterior</Link>}{page*result.data.pageSize<result.data.total&&<Link href={`?${new URLSearchParams({page:String(page+1),q})}`}>Próxima</Link>}</div></div><section className="admin-panel"><div className="admin-panel-title"><h2>Categorias</h2><span>{categories.data.items.length}</span></div><div className="admin-note">{categories.data.items.map(c=><details key={`${c.id}-${c.revision}`}><summary>{c.name} · {c.status==='active'?'Ativa':'Indisponível'}</summary>{can(admin,'PRODUCTS_UPDATE')&&!admin.readOnly&&<CategoryEditor category={c} canDisable={can(admin,'PRODUCTS_DISABLE')}/>}</details>)}</div>{can(admin,'PRODUCTS_CREATE')&&!admin.readOnly&&<CategoryEditor canDisable={can(admin,'PRODUCTS_DISABLE')}/>}</section></>;
}
